ALTER TABLE bairro ADD COLUMN id_ubs BIGINT(20);

ALTER TABLE bairro ADD CONSTRAINT fk_ubs FOREIGN KEY(id_ubs) REFERENCES ubs(id_ubs);

ALTER TABLE bairro DROP COLUMN cep;

ALTER TABLE residencia ADD COLUMN cep VARCHAR(20) NOT NULL;